### ISSUE TITLE
Improve support for the layout of empty nodes for the new algorithm

### ISSUE THREAD

**Issue by sbegaudeau** [eclipse-sirius/sirius-web#1923]
## Preliminary tasks

- [x] https://github.com/eclipse-sirius/sirius-components/pull/1947

## Tasks

- [x] https://github.com/eclipse-sirius/sirius-components/issues/1970
- [x] https://github.com/eclipse-sirius/sirius-components/issues/1971
- [x] https://github.com/eclipse-sirius/sirius-components/issues/1831
- [x] https://github.com/eclipse-sirius/sirius-components/issues/1982
- [ ] https://github.com/eclipse-sirius/sirius-components/issues/1980
- [ ] Add some details regarding the various layout strategies
- [ ] The layout engine should be aware of the different layout strategies (only support free-form layout for now)
- [ ] Cleanup `DiagramCreationService`, removes the use of `IRepresentationDescriptionSearchService` and `IObjectService`.
