### ISSUE TITLE
Add support for optional help text on widgets

### ISSUE THREAD

**Issue by pcdavid** [eclipse-sirius/sirius-web#1988]
In Sirius Desktop's EEF-based property views, it is possible to associate a help text on widgets that can display additional text in a tooltip.
We should also support this kind of mechanism in our Forms (including in View-based forms).

## Tasks

- [x] [Shape written](https://github.com/eclipse-sirius/sirius-components/pull/1987)
- [x] ADR written
- [x] Core support for `AbstractWidget[Description].helpTextProvider` and `hasHelpText` flag.
- [x] Implement the GraphQL Query to invoke a widget's `helpTextProvider`.
- [x] Frontend: display the "?" hint for widgets with `hasHelpText` (need more discussion on the icon and layout)
- [x] Frontend: invoke the GraphQL Query and display the result (as a tooltip)
- [x] View: add `WidgetDescription.helpTextExpression`
- [x] View: create a proper `helpTextProvider` from the expression during the View conversion.
- [x] Frontend: display the "?" hint in the FormDescriptionEditor version of the widgets (if the `helpTextExpression` is defined)
- [x] Add tests
- [x] Update documentation and CHANGELOG with a screenshot/animation.

**Comment by pcdavid** [comment]
https://github.com/eclipse-sirius/sirius-components/issues/1651 mentions the use of MUI's [input adornments](https://v4.mui.com/components/text-fields/#input-adornments) instead of an icon at the same level as the widget's title. I'll have a look but it's not clear that it would be applicable to all kinds of widgets in a uniform way (e.g. radio buttons, or more gererally custom widgets).

**Comment by pcdavid** [comment]
The shape was merged, but not the actual implementation.
