### ISSUE TITLE
Default form description provider should take EMF meta models into account regarding the read-only feature

### ISSUE THREAD

**Issue by jerome-obeo** [eclipse-sirius/sirius-web#2163]
* [x] **I have checked that this bug has not yet been reported by someone else**
* [x] **I have checked that this bug appears on Chrome**
* [x] **I have specified the version** :
 
Latest

* [x] **I have specified my environment** : 

All

### Problematic 

Meta models expressed with EMF specify their features with a `changeable ` flag. This means that if this flag is `false`, the feature won't be editable and should be displayed as read-only.
The default form description provider should take into account this changeableness when it provides all widget descriptions for features of the selected element.

Papyrus web Advanced page of Details panel leverages this default form description provider in order to display agnostic widgets for all features of the selected element. This is confusing that a feature that is declared as read-only can be changed in that page.

![image](https://github.com/eclipse-sirius/sirius-components/assets/128463513/624d51b6-fccd-4dac-b3b1-3fc05d7d1d23)
![image](https://github.com/eclipse-sirius/sirius-components/assets/128463513/55ab5c9e-2ac9-443f-8ffe-29d087ee62cb)

Impact on:

- `org.eclipse.sirius.components.compatibility.emf.properties.EStringIfDescriptionProvider`
- `org.eclipse.sirius.components.compatibility.emf.properties.EBooleanIfDescriptionProvider`
- `org.eclipse.sirius.components.compatibility.emf.properties.EEnumIfDescriptionProvider`
- `org.eclipse.sirius.components.compatibility.emf.properties.MonoValuedNonContainmentReferenceIfDescriptionProvider`
- `org.eclipse.sirius.components.compatibility.emf.properties.MultiValuedNonContainmentReferenceIfDescriptionProvider`

### Steps to reproduce

Using the UML meta model for instance:

1. create a Class element
2. Select this node in the Explorer
3. Open Details panel if needed

### Expected behavior

 In Advanced page, `Qualifed name` should be read-only:

![image](https://github.com/eclipse-sirius/sirius-components/assets/128463513/4728f4ac-cf0d-4023-8e32-c291ea8667af)

### Actual behavior

 In Advanced page, `Qualifed name`, which is declared in the meta model as rad-only can be modified:

![image](https://github.com/eclipse-sirius/sirius-components/assets/128463513/cd3f52f8-611a-4161-a372-c06edc97e38f)

...

**Comment by AxelRICHARD** [comment]
What do you think about a Label widget instead of a read-only Textfield widget?

**Comment by jerome-obeo** [comment]
I think Label for non editable Textfield would be nice. 
Do you plan to go further and convert read-only widgets (all kinds) into a textual representation with Label? For instance, a read-only Select is only the default entry as a String, a List could be flattened as a coma separated String of values etc...
Maybe this approach is too much.
